on:
  push:
    # tags:
    # - 'v*'

name: Upload Release Asset

jobs:
  build-on-linux:
    name: Get Package Version and upload Linux release asset
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.test }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: version
        run: |
          npm i -g json
          PACKAGE_VERSION=$(json version -a < package.json)
          echo "test=$PACKAGE_VERSION" >> $GITHUB_OUTPUT

  build-on-mac:
    needs: build-on-linux
    name: Upload Mac Release Asset
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npm run electron:mac
          zip Keira3${{needs.build-on-linux.outputs.version}}.MAC.dmg.zip release/Keira3${{needs.build-on-linux.outputs.version}}.dmg
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{needs.build-on-linux.outputs.version}}
          release_name: ${{needs.build-on-linux.outputs.version}}
          draft: true
          prerelease: false
          files: Keira3${{needs.build-on-linux.outputs.version}}.MAC.dmg.zip
      # - name: Upload binaries to release
      #   uses: svenstaro/upload-release-action@v2
      #   run: touch file.txt
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: file.txt
      #     asset_name: file.txt
      #     tag: ${{needs.build-on-linux.outputs.version}}
      #     overwrite: true
      #     body: "This is my release text"
